In [9]:
from connect import cursor
import pandas as pd

Pesquisa no Banco de dados, teste de conexao

In [13]:
cursor.execute("select * from coffe_sales cs ")

InFailedSqlTransaction: current transaction is aborted, commands ignored until end of transaction block

fetchall - Retornando pesquisa do banco de dados

In [66]:
row = cursor.fetchall()

In [67]:
df = pd.DataFrame(row)

In [68]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,08/2012,201208,19370363,44381455,63751818,193976530,0.1,0.23,0.33,5265743,...,18162964,14144,86593,100737,7927,57407,65334,119,757,876
1,09/2012,201209,19371279,44554715,63925994,193976530,0.1,0.23,0.33,5278170,...,18284925,14157,87216,101373,8022,58018,66040,123,825,948
2,10/2012,201210,19376665,44652093,64028758,193976530,0.1,0.23,0.33,5288902,...,18365268,14171,87397,101568,8081,58468,66549,131,888,1019
3,11/2012,201211,19381040,44723215,64104255,193976530,0.1,0.23,0.33,5298295,...,18429654,14182,87697,101879,8198,59193,67391,142,925,1067
4,12/2012,201212,19392882,44684759,64077641,193976530,0.1,0.23,0.33,5311337,...,18472436,14209,87820,102029,8314,60250,68564,143,978,1121

In [13]:
df[0] = pd.to_datetime(df[0])

In [34]:
df.head()

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
0,2012-08-01,201208,19370363,44381455,63751818,193976530,0.1,0.23,0.33,5265743,...,18162964,14144,86593,100737,7927,57407,65334,119,757,876
1,2012-09-01,201209,19371279,44554715,63925994,193976530,0.1,0.23,0.33,5278170,...,18284925,14157,87216,101373,8022,58018,66040,123,825,948
2,2012-10-01,201210,19376665,44652093,64028758,193976530,0.1,0.23,0.33,5288902,...,18365268,14171,87397,101568,8081,58468,66549,131,888,1019
3,2012-11-01,201211,19381040,44723215,64104255,193976530,0.1,0.23,0.33,5298295,...,18429654,14182,87697,101879,8198,59193,67391,142,925,1067
4,2012-12-01,201212,19392882,44684759,64077641,193976530,0.1,0.23,0.33,5311337,...,18472436,14209,87820,102029,8314,60250,68564,143,978,1121

In [63]:
media_2018 = df[(df[0] >= '2018-01-01') & (df[0] <= '2018-12-31')]

In [64]:
media_2018

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
65,2018-01-01,201801,11465825,38497597,49963422,208494900,0.05,0.18,0.24,3461274,...,16059197,13996,113242,127238,10730,118265,128995,663,4388,5051
66,2018-02-01,201802,11454747,38661251,50115998,208494900,0.05,0.19,0.24,3466055,...,16153812,14049,113731,127780,10717,118839,129556,659,4448,5107
67,2018-03-01,201803,10656930,37850905,48507835,208494900,0.05,0.18,0.23,3234071,...,15662288,13465,112685,126150,10194,117931,128125,663,4465,5128
68,2018-04-01,201804,10671450,38156036,48827486,208494900,0.05,0.18,0.23,3248912,...,15820407,13597,113719,127316,10233,118962,129195,669,4549,5218
69,2018-05-01,201805,10665254,38596762,49262016,208494900,0.05,0.19,0.24,3260595,...,16029206,13603,115087,128690,10343,120520,130863,676,4616,5292
70,2018-06-01,201806,10683385,38737903,49421288,208494900,0.05,0.19,0.24,3274295,...,16132031,13708,115784,129492,10507,121455,131962,693,4635,5328
71,2018-07-01,201807,10939217,39092794,50032011,208494900,0.05,0.19,0.24,3347801,...,16351559,13979,116520,130499,10753,122164,132917,682,4705,5387
72,2018-08-01,201808,10317936,38618458,48936394,208494900,0.05,0.19,0.23,3164743,...,16017366,13530,115568,129098,10331,121849,132180,668,4737,5405
73,2018-09-01,201809,10375048,38685526,49060574,208494900,0.05,0.19,0.24,3193885,...,16125949,13729,115941,129670,10476,122636,133112,679,4839,5518
74,2018-10-01,201810,10305688,38540579,48846267,208494900,0.05,0.18,0.23,3193011,...,16159153,13883,115937,129820,10570,123282,133852,740,4889,5629
75,2018-11-01,201811,10329147,38562777,48891924,208494900,0.05,0.18,0.23,3208674,...,16232201,13996,116284,130280,10707,123932,134639,743,4935,5678
76,2018-12-01,201812,9679720,37766288,47446008,208494900,0.05,0.18,0.23,3006575,...,15757243,13447,114609,128056,10294,122978,133272,708,4915,5623

/tmp/ipykernel_13440/1017516760.py:1: UserWarning: obj.round has no effect with datetime, timedelta, or period dtypes. Use obj.dt.round(...) instead.
  round(media_2018, 2)

,0,1,2,3,4,5,6,7,8,9,...,11,12,13,14,15,16,17,18,19,20
65,2018-01-01,201801,11465825,38497597,49963422,208494900,0.05,0.18,0.24,3461274,...,16059197,13996,113242,127238,10730,118265,128995,663,4388,5051
66,2018-02-01,201802,11454747,38661251,50115998,208494900,0.05,0.19,0.24,3466055,...,16153812,14049,113731,127780,10717,118839,129556,659,4448,5107
67,2018-03-01,201803,10656930,37850905,48507835,208494900,0.05,0.18,0.23,3234071,...,15662288,13465,112685,126150,10194,117931,128125,663,4465,5128
68,2018-04-01,201804,10671450,38156036,48827486,208494900,0.05,0.18,0.23,3248912,...,15820407,13597,113719,127316,10233,118962,129195,669,4549,5218
69,2018-05-01,201805,10665254,38596762,49262016,208494900,0.05,0.19,0.24,3260595,...,16029206,13603,115087,128690,10343,120520,130863,676,4616,5292
70,2018-06-01,201806,10683385,38737903,49421288,208494900,0.05,0.19,0.24,3274295,...,16132031,13708,115784,129492,10507,121455,131962,693,4635,5328
71,2018-07-01,201807,10939217,39092794,50032011,208494900,0.05,0.19,0.24,3347801,...,16351559,13979,116520,130499,10753,122164,132917,682,4705,5387
72,2018-08-01,201808,10317936,38618458,48936394,208494900,0.05,0.19,0.23,3164743,...,16017366,13530,115568,129098,10331,121849,132180,668,4737,5405
73,2018-09-01,201809,10375048,38685526,49060574,208494900,0.05,0.19,0.24,3193885,...,16125949,13729,115941,129670,10476,122636,133112,679,4839,5518
74,2018-10-01,201810,10305688,38540579,48846267,208494900,0.05,0.18,0.23,3193011,...,16159153,13883,115937,129820,10570,123282,133852,740,4889,5629
75,2018-11-01,201811,10329147,38562777,48891924,208494900,0.05,0.18,0.23,3208674,...,16232201,13996,116284,130280,10707,123932,134639,743,4935,5678
76,2018-12-01,201812,9679720,37766288,47446008,208494900,0.05,0.18,0.23,3006575,...,15757243,13447,114609,128056,10294,122978,133272,708,4915,5623